// Package tracks holds circuit layouts (outline and corners) generated by
// cmd/trackgen, and renders them as images.
//
// Coordinates are in the same frame as OpenF1 car locations, so cars can be
// plotted directly onto a track.
package tracks

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"path"
	"slices"
	"strconv"
	"strings"
)

//go:embed data
var data embed.FS

// Paths of the track files, relative to this package. cmd/trackgen writes
// the circuit files.
const (
	CircuitsDir = "data/circuits"
	CornersFile = "data/corners.json"
)

var ErrUnknownCircuit = errors.New("unknown circuit")

type Track struct {
	CircuitID  string  `json:"circuit_id"`
	CircuitKey int     `json:"circuit_key"`
	Name       string  `json:"name"`
	Locality   string  `json:"locality"`
	Country    string  `json:"country"`
	Year       int     `json:"year"`
	Rotation   float64 `json:"rotation"`
	// Outline is the racing line in lap order, starting at the start/finish line.
	Outline []Point `json:"outline"`
	// SectorStarts are the outline indices where sectors 2 and 3 begin
	// (sector 1 begins at index 0). Empty if unknown.
	SectorStarts []int    `json:"sector_starts,omitempty"`
	Corners      []Corner `json:"corners"`
}

// Point is an [x, y] position in OpenF1's track coordinate frame.
type Point [2]float64

type Corner struct {
	Number int `json:"number"`
	// Name is filled from data/corners.json when the corner has one.
	Name     string `json:"name,omitempty"`
	Position Point  `json:"position"`
	// Angle is the direction, in degrees, to place the corner's label away
	// from the track.
	Angle float64 `json:"angle"`
}

// FileName returns the track file name for a circuit and year.
func FileName(circuitID string, year int) string {
	return fmt.Sprintf("%s-%d.json", circuitID, year)
}

// Load returns the layout of a circuit for a year. If there is no file for
// that year it uses the closest earlier year, then the closest later one.
func Load(circuitID string, year int) (*Track, error) {
	years, err := Years(circuitID)
	if err != nil {
		return nil, err
	}
	pick := years[0]
	for _, y := range years {
		if y <= year {
			pick = y
		}
	}
	b, err := data.ReadFile(path.Join(CircuitsDir, FileName(circuitID, pick)))
	if err != nil {
		return nil, err
	}
	var t Track
	if err := json.Unmarshal(b, &t); err != nil {
		return nil, fmt.Errorf("decoding %s %d: %w", circuitID, pick, err)
	}
	names, err := cornerNames()
	if err != nil {
		return nil, err
	}
	for i, c := range t.Corners {
		t.Corners[i].Name = names[circuitID][strconv.Itoa(c.Number)]
	}
	return &t, nil
}

// Layout is a version of a circuit used for a run of consecutive seasons
// with data.
type Layout struct {
	From, To int
}

// Years returns the layout's seasons as a label, e.g. "2023–2026".
func (l Layout) Years() string {
	if l.From == l.To {
		return strconv.Itoa(l.From)
	}
	return fmt.Sprintf("%d–%d", l.From, l.To)
}

// Layouts returns the distinct layouts of a circuit in season order. A new
// layout starts whenever the track changes from one season to the next.
func Layouts(circuitID string) ([]Layout, error) {
	years, err := Years(circuitID)
	if err != nil {
		return nil, err
	}
	return groupLayouts(years, func(y int) (*Track, error) { return Load(circuitID, y) })
}

func groupLayouts(years []int, load func(int) (*Track, error)) ([]Layout, error) {
	var out []Layout
	var prev *Track
	for _, y := range years {
		t, err := load(y)
		if err != nil {
			return nil, err
		}
		if prev != nil && sameLayout(prev, t) {
			out[len(out)-1].To = y
		} else {
			out = append(out, Layout{From: y, To: y})
		}
		prev = t
	}
	return out, nil
}

func sameLayout(a, b *Track) bool {
	return a.Rotation == b.Rotation && slices.Equal(a.Outline, b.Outline) &&
		slices.Equal(a.SectorStarts, b.SectorStarts) && slices.Equal(a.Corners, b.Corners)
}

// Circuits returns the IDs of all circuits with track data, sorted.
func Circuits() ([]string, error) {
	all, err := index()
	if err != nil {
		return nil, err
	}
	ids := make([]string, 0, len(all))
	for id := range all {
		ids = append(ids, id)
	}
	slices.Sort(ids)
	return ids, nil
}

// Years returns the years with track data for a circuit, sorted.
func Years(circuitID string) ([]int, error) {
	all, err := index()
	if err != nil {
		return nil, err
	}
	years, ok := all[circuitID]
	if !ok {
		return nil, fmt.Errorf("%w: %q", ErrUnknownCircuit, circuitID)
	}
	return years, nil
}

func index() (map[string][]int, error) {
	entries, err := fs.ReadDir(data, CircuitsDir)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}
	all := map[string][]int{}
	for _, e := range entries {
		name := strings.TrimSuffix(e.Name(), ".json")
		i := strings.LastIndex(name, "-")
		if i < 0 {
			continue
		}
		year, err := strconv.Atoi(name[i+1:])
		if err != nil {
			continue
		}
		all[name[:i]] = append(all[name[:i]], year)
	}
	for _, years := range all {
		slices.Sort(years)
	}
	return all, nil
}

// cornerNames maps circuit ID to corner number to name.
func cornerNames() (map[string]map[string]string, error) {
	b, err := data.ReadFile(CornersFile)
	if err != nil {
		return nil, err
	}
	var names map[string]map[string]string
	if err := json.Unmarshal(b, &names); err != nil {
		return nil, fmt.Errorf("decoding %s: %w", CornersFile, err)
	}
	return names, nil
}
