// Package tracks holds circuit layouts (outline and corners) generated by
// cmd/trackgen, and renders them as images.
//
// Coordinates are in the same frame as OpenF1 car locations, so cars can be
// plotted directly onto a track.
package tracks

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"path"
	"slices"
	"strconv"
	"strings"
)

//go:embed data
var data embed.FS

// Paths of the track files, relative to this package. cmd/trackgen writes
// the circuit files.
const (
	CircuitsDir = "data/circuits"
	NamesFile   = "data/names.json"
)

var ErrUnknownCircuit = errors.New("unknown circuit")

type Track struct {
	CircuitID  string  `json:"circuit_id"`
	CircuitKey int     `json:"circuit_key"`
	Name       string  `json:"name"`
	Locality   string  `json:"locality"`
	Country    string  `json:"country"`
	Year       int     `json:"year"`
	Rotation   float64 `json:"rotation"`
	// Outline is the racing line in lap order, starting at the start/finish line.
	Outline []Point `json:"outline"`
	// SectorStarts are the outline indices where sectors 2 and 3 begin
	// (sector 1 begins at index 0). Empty if unknown.
	SectorStarts []int `json:"sector_starts,omitempty"`
	// Elevation is the height of each outline point in metres above the
	// lowest point of the lap. Empty if unknown.
	Elevation []float64 `json:"elevation,omitempty"`
	Corners   []Corner  `json:"corners"`
	// Straights are filled from data/names.json.
	Straights []Straight `json:"straights,omitempty"`
	// MarshalSectors are where each marshal sector starts, in number order.
	// Race control reports yellow flags by marshal sector.
	MarshalSectors []MarshalSector `json:"marshal_sectors,omitempty"`
}

// MarshalSector is the start of a marshal sector.
type MarshalSector struct {
	Number   int   `json:"number"`
	Position Point `json:"position"`
}

// MarshalSectorSpan returns where a marshal sector starts and ends (the start
// of the next one, wrapping round the lap).
func (t *Track) MarshalSectorSpan(number int) (from, to Point, ok bool) {
	for i, m := range t.MarshalSectors {
		if m.Number == number {
			next := t.MarshalSectors[(i+1)%len(t.MarshalSectors)]
			return m.Position, next.Position, true
		}
	}
	return Point{}, Point{}, false
}

// Straight is a named straight between two corners.
type Straight struct {
	Name string `json:"name"`
	From int    `json:"from"` // corner number at the start of the straight
	To   int    `json:"to"`   // corner number at the end
}

// Point is an [x, y] position in OpenF1's track coordinate frame.
type Point [2]float64

type Corner struct {
	Number int `json:"number"`
	// Name is filled from data/names.json when the corner has one. Corners
	// in a named complex (e.g. Raidillon, turns 3-4) share its name.
	Name string `json:"name,omitempty"`
	// AltName is another name the corner is known by, e.g. Peraltada for
	// Mexico City's Mansell Corner.
	AltName  string `json:"alt_name,omitempty"`
	Position Point  `json:"position"`
	// Angle is the direction, in degrees, to place the corner's label away
	// from the track.
	Angle float64 `json:"angle"`
}

// FileName returns the track file name for a circuit and year.
func FileName(circuitID string, year int) string {
	return fmt.Sprintf("%s-%d.json", circuitID, year)
}

// Load returns the layout of a circuit for a year. If there is no file for
// that year it uses the closest earlier year, then the closest later one.
func Load(circuitID string, year int) (*Track, error) {
	years, err := Years(circuitID)
	if err != nil {
		return nil, err
	}
	pick := years[0]
	for _, y := range years {
		if y <= year {
			pick = y
		}
	}
	b, err := data.ReadFile(path.Join(CircuitsDir, FileName(circuitID, pick)))
	if err != nil {
		return nil, err
	}
	var t Track
	if err := json.Unmarshal(b, &t); err != nil {
		return nil, fmt.Errorf("decoding %s %d: %w", circuitID, pick, err)
	}
	names, err := loadNames()
	if err != nil {
		return nil, err
	}
	if n, ok := names[circuitID]; ok {
		if err := n.apply(&t); err != nil {
			return nil, fmt.Errorf("%s in %s: %w", circuitID, NamesFile, err)
		}
	}
	return &t, nil
}

// Layout is a version of a circuit used for a run of consecutive seasons
// with data.
type Layout struct {
	From, To int
}

// Years returns the layout's seasons as a label, e.g. "2023–2026".
func (l Layout) Years() string {
	if l.From == l.To {
		return strconv.Itoa(l.From)
	}
	return fmt.Sprintf("%d–%d", l.From, l.To)
}

// Layouts returns the distinct layouts of a circuit in season order. A new
// layout starts whenever the track changes from one season to the next.
func Layouts(circuitID string) ([]Layout, error) {
	years, err := Years(circuitID)
	if err != nil {
		return nil, err
	}
	return groupLayouts(years, func(y int) (*Track, error) { return Load(circuitID, y) })
}

func groupLayouts(years []int, load func(int) (*Track, error)) ([]Layout, error) {
	var out []Layout
	var prev *Track
	for _, y := range years {
		t, err := load(y)
		if err != nil {
			return nil, err
		}
		if prev != nil && sameLayout(prev, t) {
			out[len(out)-1].To = y
		} else {
			out = append(out, Layout{From: y, To: y})
		}
		prev = t
	}
	return out, nil
}

func sameLayout(a, b *Track) bool {
	return a.Rotation == b.Rotation && slices.Equal(a.Outline, b.Outline) &&
		slices.Equal(a.SectorStarts, b.SectorStarts) && slices.Equal(a.Corners, b.Corners) &&
		slices.Equal(a.Straights, b.Straights) && slices.Equal(a.Elevation, b.Elevation)
}

// Circuits returns the IDs of all circuits with track data, sorted.
func Circuits() ([]string, error) {
	all, err := index()
	if err != nil {
		return nil, err
	}
	ids := make([]string, 0, len(all))
	for id := range all {
		ids = append(ids, id)
	}
	slices.Sort(ids)
	return ids, nil
}

// Years returns the years with track data for a circuit, sorted.
func Years(circuitID string) ([]int, error) {
	all, err := index()
	if err != nil {
		return nil, err
	}
	years, ok := all[circuitID]
	if !ok {
		return nil, fmt.Errorf("%w: %q", ErrUnknownCircuit, circuitID)
	}
	return years, nil
}

func index() (map[string][]int, error) {
	entries, err := fs.ReadDir(data, CircuitsDir)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}
	all := map[string][]int{}
	for _, e := range entries {
		name := strings.TrimSuffix(e.Name(), ".json")
		i := strings.LastIndex(name, "-")
		if i < 0 {
			continue
		}
		year, err := strconv.Atoi(name[i+1:])
		if err != nil {
			continue
		}
		all[name[:i]] = append(all[name[:i]], year)
	}
	for _, years := range all {
		slices.Sort(years)
	}
	return all, nil
}

// circuitNames are the corner and straight names of one circuit in
// data/names.json. Corner keys are a turn number ("5") or a range of turns
// sharing a name ("3-4").
type circuitNames struct {
	Corners   map[string]cornerName `json:"corners"`
	Straights []Straight            `json:"straights"`
}

// cornerName is either a plain name ("Copse") or a name with an
// alternative ({"name": "Mansell Corner", "alt": "Peraltada"}).
type cornerName struct {
	Name string `json:"name"`
	Alt  string `json:"alt"`
}

func (n *cornerName) UnmarshalJSON(b []byte) error {
	if len(b) > 0 && b[0] == '"' {
		return json.Unmarshal(b, &n.Name)
	}
	type plain cornerName
	return json.Unmarshal(b, (*plain)(n))
}

func loadNames() (map[string]circuitNames, error) {
	b, err := data.ReadFile(NamesFile)
	if err != nil {
		return nil, err
	}
	var names map[string]circuitNames
	if err := json.Unmarshal(b, &names); err != nil {
		return nil, fmt.Errorf("decoding %s: %w", NamesFile, err)
	}
	return names, nil
}

func (n circuitNames) apply(t *Track) error {
	for key, name := range n.Corners {
		from, to, err := parseTurns(key)
		if err != nil {
			return err
		}
		for i, c := range t.Corners {
			if c.Number >= from && c.Number <= to {
				t.Corners[i].Name = name.Name
				t.Corners[i].AltName = name.Alt
			}
		}
	}
	t.Straights = n.Straights
	return nil
}

// parseTurns parses "5" or "3-4".
func parseTurns(key string) (from, to int, err error) {
	a, b, isRange := strings.Cut(key, "-")
	if from, err = strconv.Atoi(a); err != nil {
		return 0, 0, fmt.Errorf("bad turn %q", key)
	}
	to = from
	if isRange {
		if to, err = strconv.Atoi(b); err != nil || to < from {
			return 0, 0, fmt.Errorf("bad turn range %q", key)
		}
	}
	return from, to, nil
}
