package main

import (
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/mariuspot/f1mcp/internal/tracks"
)

// galleryLayout is one rendered layout of a circuit.
type galleryLayout struct {
	Dir   string // directory the images are in, relative to the gallery
	Years string
	Track *tracks.Track
}

// TurnFile returns the image file of a corner.
func (galleryLayout) TurnFile(n int) string { return fmt.Sprintf("turn-%02d.png", n) }

// Named returns how many corners have a name.
func (g galleryLayout) Named() int {
	n := 0
	for _, c := range g.Track.Corners {
		if c.Name != "" {
			n++
		}
	}
	return n
}

// writeGallery writes index.html listing every layout, and an index.html in
// each layout's directory showing its map and corners.
func writeGallery(out string, layouts []galleryLayout) error {
	slices.SortFunc(layouts, func(a, b galleryLayout) int {
		return strings.Compare(a.Track.Name+a.Years, b.Track.Name+b.Years)
	})
	if err := writeTemplate(filepath.Join(out, "index.html"), indexTmpl, layouts); err != nil {
		return err
	}
	for _, l := range layouts {
		if err := writeTemplate(filepath.Join(out, l.Dir, "index.html"), layoutTmpl, l); err != nil {
			return err
		}
	}
	return nil
}

func writeTemplate(file string, t *template.Template, data any) error {
	f, err := os.Create(file)
	if err != nil {
		return err
	}
	if err := t.Execute(f, data); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

const galleryCSS = `
:root { --bg: #15151E; --card: #1F1F2A; --text: #FFFFFF; --muted: #9A9AA8; --red: #E10600; }
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--text);
  font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 1400px; margin: 0 auto; padding: 32px 20px 64px; }
header { border-bottom: 3px solid var(--red); padding-bottom: 16px; margin-bottom: 28px; }
h1 { margin: 0; font-size: 32px; }
h2 { margin: 36px 0 16px; font-size: 22px; }
.muted, header p { color: var(--muted); margin: 6px 0 0; }
a { color: inherit; text-decoration: none; }
a:hover .title { color: var(--red); }
.grid { display: grid; gap: 20px; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); }
.card { background: var(--card); border-radius: 10px; overflow: hidden; display: block; }
.card img { width: 100%; display: block; aspect-ratio: 4 / 3; object-fit: cover; }
.card .info { padding: 12px 14px 14px; }
.title { font-weight: 700; }
.map { width: 100%; border-radius: 10px; display: block; }
.back { display: inline-block; margin-bottom: 12px; color: var(--muted); }
.back:hover { color: var(--text); }
footer { margin-top: 48px; color: var(--muted); font-size: 13px; }
`

const galleryFooter = `<footer>Track data: <a href="https://multiviewer.app">MultiViewer</a>,
<a href="https://openf1.org">OpenF1</a> and <a href="https://github.com/jolpica/jolpica-f1">Jolpica</a>;
corner names from Wikipedia. Generated by <a href="https://github.com/mariuspot/f1mcp">f1mcp</a>.
Unofficial and not associated with Formula 1.</footer>`

var indexTmpl = template.Must(template.New("index").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>F1 track maps</title>
<style>` + galleryCSS + `</style>
</head>
<body>
<main>
<header>
<h1>F1 track maps</h1>
<p>{{len .}} circuit layouts, with timing sectors, kerbs, start/finish line and every corner.</p>
</header>
<div class="grid">
{{range .}}<a class="card" href="{{.Dir}}/">
<img src="{{.Dir}}/map.png" alt="Map of {{.Track.Name}}" loading="lazy">
<div class="info"><div class="title">{{.Track.Name}}</div>
<div class="muted">{{.Track.Locality}}, {{.Track.Country}} · {{.Years}} · {{len .Track.Corners}} turns</div></div>
</a>
{{end}}</div>
` + galleryFooter + `
</main>
</body>
</html>
`))

var layoutTmpl = template.Must(template.New("layout").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Track.Name}} {{.Years}} · F1 track maps</title>
<style>` + galleryCSS + `</style>
</head>
<body>
<main>
<a class="back" href="../">← All circuits</a>
<header>
<h1>{{.Track.Name}}</h1>
<p>{{.Track.Locality}}, {{.Track.Country}} · {{.Years}} · {{len .Track.Corners}} turns{{if .Named}}, {{.Named}} named{{end}}</p>
</header>
<a href="map.png"><img class="map" src="map.png" alt="Map of {{.Track.Name}}"></a>
<h2>Corners</h2>
<div class="grid">
{{$l := .}}{{range .Track.Corners}}<a class="card" href="{{$l.TurnFile .Number}}">
<img src="{{$l.TurnFile .Number}}" alt="Turn {{.Number}}" loading="lazy">
<div class="info"><div class="title">Turn {{.Number}}{{if .Name}} · {{.Name}}{{end}}</div>
{{if .AltName}}<div class="muted">Also known as {{.AltName}}</div>{{end}}</div>
</a>
{{end}}</div>
` + galleryFooter + `
</main>
</body>
</html>
`))
