package main

import (
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/mariuspot/f1mcp/internal/tracks"
)

// galleryLayout is one rendered layout of a circuit.
type galleryLayout struct {
	Dir   string // directory the images are in, relative to the gallery
	Years string
	Track *tracks.Track
}

// TurnFile returns the image file of a corner.
func (galleryLayout) TurnFile(n int) string { return fmt.Sprintf("turn-%02d.png", n) }

// Named returns how many corners have a name.
func (g galleryLayout) Named() int {
	n := 0
	for _, c := range g.Track.Corners {
		if c.Name != "" {
			n++
		}
	}
	return n
}

// galleryIncident is one rendered incident.
type galleryIncident struct {
	Dir        string // directory the images are in, relative to the gallery
	CornerFile string // close-up image, if any
	Incident   Incident
	Track      *tracks.Track
}

// galleryLaps is one rendered lap animation.
type galleryLaps struct {
	Dir   string
	Title string // e.g. "NOR 1:41.234 vs PIA 1:41.456"
	Laps  LapFile
	Video bool // whether the follow-camera video was made
	// Faster is whether there's a map of where each driver was faster,
	// made when there are several laps.
	Faster bool
	// Credits are the drivers' photos used in the video.
	Credits []Headshot
}

// writeGallery writes index.html listing every layout, incident and lap
// animation, and an index.html in each of their directories.
func writeGallery(out string, layouts []galleryLayout, incidents []galleryIncident, laps []galleryLaps) error {
	slices.SortFunc(layouts, func(a, b galleryLayout) int {
		return strings.Compare(a.Track.Name+a.Years, b.Track.Name+b.Years)
	})
	slices.SortFunc(incidents, func(a, b galleryIncident) int {
		return strings.Compare(b.Incident.Name, a.Incident.Name)
	})
	index := struct {
		Layouts   []galleryLayout
		Incidents []galleryIncident
		Laps      []galleryLaps
	}{layouts, incidents, laps}
	if err := writeTemplate(filepath.Join(out, "index.html"), indexTmpl, index); err != nil {
		return err
	}
	for _, l := range layouts {
		if err := writeTemplate(filepath.Join(out, l.Dir, "index.html"), layoutTmpl, l); err != nil {
			return err
		}
	}
	for _, inc := range incidents {
		if err := writeTemplate(filepath.Join(out, inc.Dir, "index.html"), incidentTmpl, inc); err != nil {
			return err
		}
	}
	for _, l := range laps {
		if err := writeTemplate(filepath.Join(out, l.Dir, "index.html"), lapsTmpl, l); err != nil {
			return err
		}
	}
	return nil
}

func writeTemplate(file string, t *template.Template, data any) error {
	f, err := os.Create(file)
	if err != nil {
		return err
	}
	if err := t.Execute(f, data); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

const galleryCSS = `
:root { --bg: #15151E; --card: #1F1F2A; --text: #FFFFFF; --muted: #9A9AA8; --red: #E10600; }
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--text);
  font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 1400px; margin: 0 auto; padding: 32px 20px 64px; }
header { border-bottom: 3px solid var(--red); padding-bottom: 16px; margin-bottom: 28px; }
h1 { margin: 0; font-size: 32px; }
h2 { margin: 36px 0 16px; font-size: 22px; }
.muted, header p { color: var(--muted); margin: 6px 0 0; }
a { color: inherit; text-decoration: none; }
a:hover .title { color: var(--red); }
.grid { display: grid; gap: 20px; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); }
.card { background: var(--card); border-radius: 10px; overflow: hidden; display: block; }
.card img { width: 100%; display: block; aspect-ratio: 4 / 3; object-fit: cover; }
.card .info { padding: 12px 14px 14px; }
.title { font-weight: 700; }
.map { width: 100%; border-radius: 10px; display: block; }
.back { display: inline-block; margin-bottom: 12px; color: var(--muted); }
.back:hover { color: var(--text); }
footer { margin-top: 48px; color: var(--muted); font-size: 13px; }
`

const galleryFooter = `<footer>Track data: <a href="https://multiviewer.app">MultiViewer</a>,
<a href="https://openf1.org">OpenF1</a> and <a href="https://github.com/jolpica/jolpica-f1">Jolpica</a>;
corner names from Wikipedia. Generated by <a href="https://github.com/mariuspot/f1mcp">f1mcp</a>.
Unofficial and not associated with Formula 1.</footer>`

var indexTmpl = template.Must(template.New("index").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>F1 track maps</title>
<style>` + galleryCSS + `</style>
</head>
<body>
<main>
<header>
<h1>F1 track maps</h1>
<p>{{len .Layouts}} circuit layouts, with timing sectors, kerbs, start/finish line, elevation and every corner.</p>
</header>
{{if .Laps}}<h2>Laps</h2>
<div class="grid">
{{range .Laps}}<a class="card" href="{{.Dir}}/">
<img src="{{.Dir}}/poster.png" alt="Lap animation" loading="lazy">
<div class="info"><div class="title">{{.Laps.Session}} {{.Laps.Year}}</div>
<div class="muted">{{.Title}}</div></div>
</a>
{{end}}</div>
{{end}}{{if .Incidents}}<h2>Incidents</h2>
<div class="grid">
{{range .Incidents}}<a class="card" href="{{.Dir}}/">
<img src="{{.Dir}}/map.png" alt="Map of {{.Incident.Session}}" loading="lazy">
<div class="info"><div class="title">{{.Incident.Session}} {{.Incident.Year}}</div>
<div class="muted">{{.Incident.Overlay.Banner}}</div>
<div class="muted">{{.Incident.Overlay.Caption}}</div></div>
</a>
{{end}}</div>
{{end}}{{if or .Incidents .Laps}}<h2>Circuits</h2>{{end}}
<div class="grid">
{{range .Layouts}}<a class="card" href="{{.Dir}}/">
<img src="{{.Dir}}/map.png" alt="Map of {{.Track.Name}}" loading="lazy">
<div class="info"><div class="title">{{.Track.Name}}</div>
<div class="muted">{{.Track.Locality}}, {{.Track.Country}} · {{.Years}} · {{len .Track.Corners}} turns</div></div>
</a>
{{end}}</div>
` + galleryFooter + `
</main>
</body>
</html>
`))

var incidentTmpl = template.Must(template.New("incident").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Incident.Session}} {{.Incident.Year}} · F1 track maps</title>
<style>` + galleryCSS + `</style>
</head>
<body>
<main>
<a class="back" href="../../">← All circuits and incidents</a>
<header>
<h1>{{.Incident.Session}} {{.Incident.Year}}</h1>
<p>{{.Incident.Overlay.Banner}}</p>
<p>{{.Incident.Overlay.Caption}}</p>
</header>
<a href="map.png"><img class="map" src="map.png" alt="Map of the incident"></a>
{{if .CornerFile}}<h2>Close-up</h2>
<a href="{{.CornerFile}}"><img class="map" src="{{.CornerFile}}" alt="Close-up of the incident"></a>{{end}}
` + galleryFooter + `
</main>
</body>
</html>
`))

var lapsTmpl = template.Must(template.New("laps").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}} · F1 track maps</title>
<style>` + galleryCSS + `</style>
</head>
<body>
<main>
<a class="back" href="../../">← All circuits, incidents and laps</a>
<header>
<h1>{{.Laps.Session}} {{.Laps.Year}}</h1>
<p>{{.Title}}</p>
</header>
{{if .Video}}<h2>Following the car</h2>
<p class="muted">Zoomed in like the corner images, with braking zones, braking speeds and gear changes.</p>
<video class="map" src="lap-follow.mp4" poster="poster.png" autoplay muted loop playsinline controls></video>
<h2>Whole track</h2>{{end}}
<img class="map" src="lap.gif" alt="Animation of {{.Title}}">
{{if .Faster}}<h2>Where each driver was faster</h2>
<p class="muted">Each corner and straight is edged in the colour of the driver who was quickest through it, faded where it was within 0.02 s. Below, the gap to the first driver all round the lap.</p>
<img class="map" src="faster.png" alt="Map of where each driver was faster, {{.Title}}">{{end}}
<h2>With braking and gear changes</h2>
<p class="muted">Red marks where each driver was on the brakes, with their speed in km/h as braking started; dots show each gear change and the new gear.</p>
<img class="map" src="lap-events.gif" alt="Animation of {{.Title}} with braking and gear changes">
{{if .Credits}}<h2>Photo credits</h2>
<p class="muted">{{range .Credits}}{{.Name}}: photo by {{.Artist}}, <a href="{{.LicenseURL}}">{{.License}}</a>, <a href="{{.Commons}}">via Wikimedia Commons</a>.<br>{{end}}
The video includes these photos and is shared under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.
Flags: <a href="https://flagcdn.com">flagcdn.com</a> (public domain).</p>{{end}}
` + galleryFooter + `
</main>
</body>
</html>
`))

var layoutTmpl = template.Must(template.New("layout").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Track.Name}} {{.Years}} · F1 track maps</title>
<style>` + galleryCSS + `</style>
</head>
<body>
<main>
<a class="back" href="../">← All circuits</a>
<header>
<h1>{{.Track.Name}}</h1>
<p>{{.Track.Locality}}, {{.Track.Country}} · {{.Years}} · {{len .Track.Corners}} turns{{if .Named}}, {{.Named}} named{{end}}</p>
</header>
<a href="map.png"><img class="map" src="map.png" alt="Map of {{.Track.Name}}"></a>
<h2>Corners</h2>
<div class="grid">
{{$l := .}}{{range .Track.Corners}}<a class="card" href="{{$l.TurnFile .Number}}">
<img src="{{$l.TurnFile .Number}}" alt="Turn {{.Number}}" loading="lazy">
<div class="info"><div class="title">Turn {{.Number}}{{if .Name}} · {{.Name}}{{end}}</div>
{{if .AltName}}<div class="muted">Also known as {{.AltName}}</div>{{end}}</div>
</a>
{{end}}</div>
` + galleryFooter + `
</main>
</body>
</html>
`))
